package trycatch_in;

public class TestRuntimeException2 {
	public void foo() {
		/*]*/throw new NullPointerException();/*[*/
	}
}
